# Generated by Django 5.2.7 on 2025-11-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('floors', models.CharField(max_length=10)),
                ('slots', models.CharField(max_length=10)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
            ],
        ),
    ]
