# Generated by Django 5.2.7 on 2025-11-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_companydetail_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('slot', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='floors',
            field=models.CharField(choices=[('GRND', 'Ground Floor'), ('F01', '1 Floor'), ('F02', '2 Floor'), ('F03', '3 Floor'), ('F04', '4 Floor'), ('F05', '5 Floor'), ('F06', '6 Floor'), ('F07', '7 Floor'), ('F08', '8 Floor'), ('F09', '9 Floor'), ('F10', '10 Floor'), ('F11', '11 Floor'), ('F12', '12 Floor')], max_length=4),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='slots',
            field=models.CharField(choices=[('S01', '1 Slot'), ('S02', '2 Slots'), ('S03', '3 Slots'), ('S04', '4 Slots'), ('S05', '5 Slots'), ('S06', '6 Slots'), ('S07', '7 Slots'), ('S08', '8 Slots'), ('S09', '9 Slots'), ('S10', '10 Slots'), ('S11', '11 Slots'), ('S12', '12 Slots')], max_length=4),
        ),
    ]
