# Generated by Django 5.2.7 on 2025-11-28 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_parkinguser_alter_companydetail_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinguser',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='slot',
            field=models.CharField(max_length=10),
        ),
    ]
