# Generated by Django 5.2.7 on 2025-11-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0004_parkinguser_login_time_alter_parkinguser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinguser',
            name='slot',
            field=models.CharField(max_length=20),
        ),
    ]
