# Generated by Django 5.2.7 on 2025-11-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0005_alter_parkinguser_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinguser',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
