# Generated by Django 5.2.7 on 2025-11-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0006_alter_parkinguser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinguser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='car_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
