# Generated by Django 5.2.7 on 2025-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0007_parkinguser_is_active_alter_parkinguser_car_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinguser',
            name='car_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='slot',
            field=models.CharField(default='Not Assigned', max_length=20),
        ),
    ]
