# Generated by Django 5.2.7 on 2025-12-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0008_alter_parkinguser_car_number_alter_parkinguser_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
