# Generated by Django 5.2.7 on 2025-12-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0009_selectedslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedSlot',
        ),
    ]
