# Generated by Django 5.2.7 on 2025-12-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0010_delete_selectedslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinguser',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
