# Generated by Django 5.2.7 on 2025-12-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0011_parkinguser_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinguser',
            name='price_per_hour',
            field=models.FloatField(default=50),
        ),
    ]
